export const DataMock = {
  BTC: [
    {
      symbol: "BTCUSD",
      symbolName: "Bitcoin",
      amount: 0.01,
      openRate: 58769,
      currentRate: 0,
      totalPrice: amount * openRate,
      platform: "Crypto.com",
    },
    {
      symbol: "BTCUSD",
      symbolName: "Bitcoin",
      amount: 0.0075,
      openRate: 40276,
      currentRate: 0,
      totalPrice: amount * openRate,
      platform: "Crypto.com",
    },
  ],
  ETH: [
    {
      symbol: "ETHUSD",
      symbolName: "Ethereum",
      amount: 0.01,
      openRate: 3290,
      currentRate: 0,
      totalPrice: amount * openRate,
      platform: "Crypto.com",
    },
    {
      symbol: "ETHUSD",
      symbolName: "Ethereum",
      amount: 0.5,
      openRate: 3388,
      currentRate: 0,
      totalPrice: amount * openRate,
      platform: "Crypto.com",
    },
    {
      symbol: "ETHUSD",
      symbolName: "Ethereum",
      amount: 0.13,
      openRate: 3054,
      currentRate: 0,
      totalPrice: amount * openRate,
      platform: "Crypto.com",
    },
    {
      symbol: "ETHUSD",
      symbolName: "Ethereum",
      amount: 0.01,
      openRate: 3290,
      currentRate: 0,
      totalPrice: amount * openRate,
      platform: "Crypto.com",
    },
  ],
};
